title: Sakae Mizuki
description: The long journey toward becoming a technical leader
github: false
show_downloads: false
google_analytics: G-0MEJ0X9TMF
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
